# values.yaml
replicaCount: 1
cluster: api.alto3sg0g25ce33bb3.eastus.aroapp.io
namespace: 896mendels
image:
  repository: mendel27/torah-discourse-app
  tag: "dev-2024-10-20-9508d4c"
  pullPolicy: Always
service:
  type: ClusterIP
  port: 8000
route:
  enabled: true
secrets:
  openai:
    name: openai
    apiKey: "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"
  docker:
    name: dockercred
    dockerconfigjson: |-
      {
          "auths": {
                  "https://index.docker.io/v1/": {
                          "auth": "bWVuZGVsMjc6ZGNrcl9wYXRfWXNLRWMtdzZ6OERVempHTVotY0hlVXItSURn"
                  },
                  "https://index.docker.io/v1/access-token": {
                        "auth": "bWVuZGVsMjc6ZXlKaGJHY2lPaUpTVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0lzSW10cFpDSTZJbmhZYTNCQ2RETnlWM015UnkxMVlqbHNjRXBuY1NKOS5leUpvZEhSd2N6b3ZMMmgxWWk1a2IyTnJaWEl1WTI5dElqcDdJbVZ0WVdsc0lqb2liV1Z1WkdWc0xuTmhZbUl5TjBCbmJXRnBiQzVqYjIwaUxDSnpaWE56YVc5dVgybGtJam9pTVRObU9HWTRZekV0WVRWaE1DMDBNRFE1TFdJek16UXRZVFU0TmpGa1ptUmlZakF6SWl3aWMyOTFjbU5sSWpvaVlYVjBhREFpTENKMWMyVnlibUZ0WlNJNkltMWxibVJsYkRJM0lpd2lkWFZwWkNJNkltRTFaalkwT0RJekxUUTJaVGN0TkRoaU9DMWlPRGd3TFRJMVlUUXdOR0prTmpNek9DSjlMQ0pwYzNNaU9pSm9kSFJ3Y3pvdkwyeHZaMmx1TG1SdlkydGxjaTVqYjIwdklpd2ljM1ZpSWpvaVlYVjBhREI4WVRWbU5qUTRNak10TkRabE55MDBPR0k0TFdJNE9EQXRNalZoTkRBMFltUTJNek00SWl3aVlYVmtJanBiSW1oMGRIQnpPaTh2YUhWaUxtUnZZMnRsY2k1amIyMGlMQ0pvZEhSd2N6b3ZMMlJ2WTJ0bGNpMXdjbTlrTG5WekxtRjFkR2d3TG1OdmJTOTFjMlZ5YVc1bWJ5SmRMQ0pwWVhRaU9qRTNNamc1TkRjd056QXNJbVY0Y0NJNk1UY3lPRGsxTURZM01Dd2ljMk52Y0dVaU9pSnZjR1Z1YVdRZ2IyWm1iR2x1WlY5aFkyTmxjM01pTENKaGVuQWlPaUpNTkhZd1pHMXNUa0p3V1ZWcVIwZGhZakJETWtwMFoxUm5XSEl4VVhvMFpDSjkuc3UxVlB6X1FZRlZHek9pNUw5bzl5cmNvQWZSeXB6MWtoU0JOQVJSU04xTFltMUlEY0c4SzZlZlMzdWZhWFNuOGo3VGNMa2RsS0QwcEVCb2poN1dfdFNjQ1I1ZzdybktISWhyRGtLaGJTMDd4MU1LMGFXY3kyQVVfX0lpOWg5QW5VcXU3Q3JwNUxkTWNuRFVRV29kYmJGSWhZRnNQVWRiVlhqa3RiNHRGWlROa0lwcElqcXgwUkVoS21XSm03aTZOanc2NnhPN01fZDJ2Ty1xU25VM0dWT0JpX0Z2MVZCdXgzNGJ5RUNZU0p0ZlpPZFkySmJZTGtwempBdHVNUjh4blh3amJ3bzh3bUVFTU9Rdm9uQ2dJZDNaVEFSNkNxWVVNOEpGUzVBei1PV2E4NDUzV2I3VUNPVzJUTWFIZExBQkZqWXo5ZVpmR0FIamdWM1VBWVRNbUpB"
                  },
                  "https://index.docker.io/v1/refresh-token": {
                        "auth": "bWVuZGVsMjc6djEuTVhNdnpHUDdhVzlZNzBZVC1BNHBwNDhqcTZWeVVVOU5hRzZQbFoxYW9FdGV5S1ZmcDdySmxBMEIwdjQzZVV1WE1JQV8wM0tUZ2t6MldJcEFxNkRtS1ZNLi5MNHYwZG1sTkJwWVVqR0dhYjBDMkp0Z1RnWHIxUXo0ZA=="
                  }
            }
      }
