name: Docker CI/CD

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

permissions:
  contents: write  # Allow the GITHUB_TOKEN to push to the repository

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get current date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Get commit SHA
        id: vars
        run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/torah-discourse-app:${{ github.ref_name }}-${{ env.DATE }}-${{ env.COMMIT_SHA }}

  update-image-tag:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install yq
        run: |
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq && chmod +x /usr/local/bin/yq  
      
      - name: Get current date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Get commit SHA
        id: vars
        run: echo "COMMIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Update image tag in values.yaml
        run: |
          MAGE_TAG="${{ github.ref_name }}-${{ env.DATE }}-${{ env.COMMIT_SHA }}"
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          yq e ".image.tag = \"${IMAGE_TAG}\"" -i chart/values.yaml

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/mendelsabb/parasha.git

      - name: Commit and push changes
        run: |
          git add chart/values.yaml
          git commit -m "Update image tag to ${{ github.ref_name }}-${{ env.DATE }}-${{ env.COMMIT_SHA }}"
          git push origin ${{ github.ref_name }}

