name: Docker CI/CD

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get current date
      run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/torah-discourse-app:cache
        cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/torah-discourse-app:cache,mode=max
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/torah-discourse-app:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/torah-discourse-app:${{ github.ref_name }}-${{ env.DATE }}
